name: PR from External Contribution Detector

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  labeler:
    if: |
      (
        (github.event.pull_request.author_association != 'OWNER') &&
        (github.event.pull_request.author_association != 'COLLABORATOR') &&
        (github.event.pull_request.author_association != 'MEMBER')
      )
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Install Cilium CLI
        run: |
          echo author_association=${{ github.event.pull_request.author_association }}
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["kind/community-contribution"]
            })
